version: 2.1

jobs:
  # Job to run UI tests
  run_ui_tests:
    docker:
      - image: circleci/node:latest  # Use a Node.js Docker image
    working_directory: ~/TaskQA 
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install UI Test Dependencies
          command: npm install  # Install dependencies for UI tests
      - run:
          name: Run UI Tests
          command: npx nightwatch  # Run Nightwatch tests

  # Job to run API tests
  run_api_tests:
    docker:
      - image: circleci/node:latest  # Use a Node.js Docker image
    working_directory: ~/ApiTest  # Working directory for API tests
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Install API Test Dependencies
          command: npm install  # Install dependencies for API tests
      - run:
          name: Run API Tests
          command: npx mocha tests/api --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/api-test-results.xml  # Run Mocha tests

# Define workflows to run jobs in sequence
workflows:
  version: 2
  test:
    jobs:
      - run_ui_tests  # Run UI tests first
      - run_api_tests:
          requires:
            - run_ui_tests  # Only run API tests after UI tests succeed