version: 2.1

jobs:
 
  ui_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run UI tests
          command: npx nightwatch
          
  
  api_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run API tests
          command: |
            npx mocha tests/api --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/api-test-results.xml

workflows:
  version: 2
  test_workflow:
    jobs:
      - ui_tests
      - api_tests:
          requires:
            - ui_tests 