version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14  # Use the appropriate Node.js version
    resource_class: large  # Increase resource class if necessary

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  run-ui-tests:
    steps:
      - checkout
      - run:
          name: Start ChromeDriver
          command: |
            npm install chromedriver
            chromedriver --port=9515 &
      - run:
          name: Run UI Tests
          command: npm test
          environment:
            NODE_ENV: test  # Add any required environment variables here

workflows:
  version: 2
  test:
    jobs:
      - build
      - run-ui-tests:
          requires:
            - build



#   api_tests:
#     machine: true  
#     steps:
#       - checkout 
#       - run:
#           name: Install Node.js
#           command: |
#             curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
#             sudo apt-get install -y nodejs
#       - run:
#           name: List Files in Working Directory
#           command: ls -al  # List files and directories in the current path
#       - run:
#           name: Change Directory to ApiTest
#           command: |
#             cd ApiTest  
#             echo "Current directory: $(pwd)"
#       - run:
#           name: Install API test dependencies
#           command: |
#             cd ApiTest  
#             npm install
#       - run:
#           name: Run API tests
#           command: |
#             cd ApiTest  
#             npx mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/api-test-results.xml

# workflows:
#   version: 2
#   test_workflow:
#     jobs:
#       - ui_tests
#       - api_tests:
#           requires:
#             - ui_tests



# version: 2.1

# jobs:
#   api_tests:
#     machine: true  
#     steps:
#       - checkout 
#       - run:
#           name: Install Node.js
#           command: |
#             curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
#             sudo apt-get install -y nodejs
#       - run:
#           name: List Files in Working Directory
#           command: ls -al  # List files and directories in the current path
#       - run:
#           name: Change Directory to ApiTest
#           command: |
#             cd ApiTest  
#             echo "Current directory: $(pwd)"
#       - run:
#           name: Install API test dependencies
#           command: |
#             cd ApiTest  
#             npm install
#       - run:
#           name: Run API tests
#           command: |
#             cd ApiTest  
#             npx mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/api-test-results.xml

# workflows:
#   version: 2
#   test_workflow:
#     jobs:
#       - api_tests
